# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Set up Ruby
      run: brew install ruby
    
    - name: Swift Setup
      uses: YOCKOW/Action-setup-swift@v1.1.0
      with:
        # The version of Swift.
        swift-version: '5.2.2'

    # Runs a set of commands using the runners shell
    - name: Setup Vipergen Proper
      run: |
        echo Installing...
        sudo gem install vipergen
        
    - name: Create Swift Project Container
      run: |
        mkdir testModule && cd testModule
        swift package init --type executable
        
    - name: Build Viper Project
      run: |
        echo "Creating simple Project..."
        vipergen generate TestModule --path=./testModule/Sources
        cd ./testModule
        swift build
